- name: Installing Redis Repo
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true
    
- name: Enable Redis 6.2
  command: yum module enable redis:remi-6.2 -y

- name: Installing Redis
  yum:
    name: redis
    state: installed

- name: Allow remote connections to redis
  replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting and Enabling Redis
  service:
    name: redis
    state: started
    enabled: yes
