- name: Configuring yum repo script provided by MQ Vendor
  shell: "{{item}}"
  loop:
  - curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
  - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Installing RabbitMQ
  yum:
    name: rabbitmq-server
    state: installed

- name: Restarting RabbitMQ
  service:
    name: rabbitmq-server
    state: restarted
    enabled: true

- name: Creating RabbitMQ user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present