- name: copy {{component}} service file to systemd
  copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Reloading Daemon
  systemd:
    daemon_reload: true
- name: "Restarting {{component}}"
  service:
    name: "{{component}}"
    state: restarted
    enabled: yes
    