- name: Installing NodeJs
  import_role:
    name: common
    tasks_from: nodejs

- name: Setup Application (roboshop user creation, /app dir, downloading and unzipping artifacts)
  import_role:
    name: common
    tasks_from: app-setup

- name: Change the directory to /app and install dependencies
  command: npm install
  args:
    chdir: /app

- name: Copying service file and reloading service
  import_role:
    name: common
    tasks_from: systemd-setup